
obj-libbench	=
obj-libbench 	= func_bench.o

deps-libbench	=

target-libbench	= build/libbench.a

$(eval $(call build_library,\
	$(target-libbench),\
	$(obj-libbench),\
	$(deps-libbench),\
	bench,\
))

