
obj-libcvector	=

deps-libcvector	=

target-libcvector	= build/libcvector.a

$(eval $(call build_library,\
	$(target-libcvector),\
	$(obj-libcvector),\
	$(deps-libcvector),\
	container/cvector,\
))

